#!/bin/sh /etc/rc.common

START=99

run_helper() {
	local helper="$1"

	command -v "$helper" >/dev/null 2>&1 || return 0
	"$helper"
}

boot() {
	run_helper alemprator_f
}

start() {
	run_helper alemprator_s
}

reload() {
	reload_service
}

reload_service() {
	start
}

restart() {
	start
}
